### PR TITLE
Frontend - using react-scripts on npm dependencies

### PR DESCRIPTION
**Pull request by pacostas**
Merge after https://github.com/nodeshift/mern-workshop/pull/74 due to it is rebased on it.

### CODE REVIEW

**Comment by pacostas** [comment]
I had issues with installing the packages, due to different versions of the dependencies of the packages. Eventually I used the ones that react-scripts has where in that case succeeds in npm install. I'm not sure if this is aligned with what snyk thinks, but I trust react-scripts.

**Comment by pacostas** [comment]
This PR does not `npm run build` with error `[webpack-cli] TypeError: compiler.plugin is not a function
` despite `npm run serve` works.
I'm not quite sure how to update the dependencies. I think we should have a discussion about If we should spend more time on trying to resolve the dependencies or if we should use react-scripts instead adding the dependences separately on package.json

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by lholmquist** [comment]
closed via [051e557](https://github.com/nodeshift/mern-workshop/commit/051e5574124dce220158dcaca7200b5fa00d4e75)

**Pull request closed without merging**
